---
- name: Build R analysis Docker image
  command: >
    docker build
      -f {{ root_analysis_dir }}/Dockerfile
      -t {{ docker_repository }}/driver-analysis:{{ docker_image_tag }}
      {{ root_analysis_dir }}
  when: developing

- name: Pull application Docker image
  command: /usr/bin/docker pull {{ docker_repository }}/driver-analysis:{{ docker_image_tag }}
  when: staging or production
