---
# Dependencies for driver.database role
dependencies:
  - { role: "azavea.postgresql" }
  - { role: "azavea.postgresql-support"}
  - { role: "azavea.postgis" }
  - { role: "driver.redis" }
  - { role: "driver.monit" }
