---
driver_user: "{{ ansible_ssh_user }}"
driver_conf:
  DRIVER_ADMIN_USERNAME: "{{ driver_admin_username }}"
  DRIVER_ADMIN_PASSWORD: "{{ driver_admin_password }}"
  DRIVER_ADMIN_EMAIL: "{{ driver_admin_email }}"
  DRIVER_DB_NAME: "{{ postgresql_database }}"
  DRIVER_DB_USER: "{{ postgresql_username }}"
  DRIVER_DB_PASSWORD: "{{ postgresql_password }}"
  WINDSHAFT_DB_USER: "{{ windshaft_db_username }}"
  WINDSHAFT_DB_PASSWORD: "{{ windshaft_db_password }}"
  DRIVER_DB_HOST: "{{ postgresql_host }}"
  DRIVER_DB_PORT: "{{ postgresql_port }}"
  DRIVER_APP_HOST: "{{ driver_app_hostname }}"
  OAUTH_CLIENT_ID: "{{ oauth_client_id }}"
  OAUTH_CLIENT_SECRET: "{{ oauth_client_secret }}"
  FORECAST_IO_API_KEY: "{{ forecast_io_api_key }}"
  DRIVER_REDIS_HOST: "{{ redis_bind_address }}"
  DRIVER_REDIS_PORT: "{{ redis_port }}"
  DJANGO_STATIC_ROOT: "{{ root_static_dir }}"
  DJANGO_MEDIA_ROOT: "{{ root_media_dir }}"
  DJANGO_POSTGIS_VERSION: "{{ driver_postgis_version }}"
  DJANGO_SECRET_KEY: "{{ postgresql_password | md5 }}"
  DJANGO_ENV: "{% if developing %}development{% elif staging %}staging{% else %}production{% endif %}"
  ALLOWED_HOST: "{{ allowed_host }}"

driver_postgis_version: 2.1.3

root_app_dir: "/opt/app"
root_www_dir: "/var/www"
root_windshaft_dir: "/opt/windshaft"
root_static_dir: "{{ root_www_dir }}/static"
root_media_dir: "{{ root_www_dir }}/media"

nginx_server_name: "{% if allowed_host %}{{ allowed_host }}{% else %}_{% endif %}"
